### ISSUE TITLE
schema location for gco in fcc/1.0/abstract.xsd for 19110

### ISSUE THREAD

**Issue by smrgeoinfo** [ISO-TC211/XML#144]
current schema location for gco at http:standards.iso.org/iso/19110/fcc/1.0/abstract.xsd is incorrect. It should be schemaLocation="../../../../iso/19115/-3/gco/1.0/gco.xsd.

problem is that the directory structure on the live web is slightly different from githup directory structure, so relative path in gitHub is different from relative path on the web. Have to update the doc on the web.
@tedhabermann -- can you do this?

**Comment by tedhabermann** [comment]
@smrgeoinfo - I think the correct path is actually ../../../19115/-3/gco/1.0/gco.xsd. The difference for the ccc directory is related to the lack of a standard part number directory under the 19110. In other words, the directory structure is 
standards.iso.org/iso/19110/fcc instead of
standards.iso.org/iso/19110/-1/fcc

I have changed this path this morning.

**Comment by alwalsh** [comment]
Hi Ted and Steve,

I have been testing the latest schema zip from http://standards.iso.org/ and concur with that path fix. The fcc/1.0/abstract.xsd in http://standards.iso.org/iso/19115/19115Allnamespaces.zip doesn't have the fix yet. Could the 19115Allnamespaces.zip be updated with the fix from github?

Regards,
Andrew Walsh
